---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mytom-deploy
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mytom
    spec:
      containers:
      - name: tomcat-pod-dp
        image: Rameshdutt80/tomcat
        ports:
        - containerPort: 8080

